#ifndef _SMARTRF_SETTINGS_433_H_
#define _SMARTRF_SETTINGS_433_H_

//*********************************************************************************
// Generated by SmartRF Studio version 2.14.0 (build#189)
// The applied template is compatible with CC13x0 SDK version 2.10.xx.xx or newer.
// Device: CC1350 Rev. B (2.1)
//
//*********************************************************************************
#include <ti/devices/DeviceFamily.h>
#include DeviceFamily_constructPath(driverlib/rf_mailbox.h)
#include DeviceFamily_constructPath(driverlib/rf_common_cmd.h)
#include DeviceFamily_constructPath(driverlib/rf_prop_cmd.h)
#include <ti/drivers/rf/RF.h>


// TI-RTOS RF Mode Object
extern RF_Mode RF_prop;

// RF Core API commands
extern rfc_CMD_PROP_RADIO_DIV_SETUP_t RF_cmdPropRadioDivSetup;
extern rfc_CMD_FS_t RF_cmdFs;
extern rfc_CMD_PROP_RX_t RF_cmdPropRx;
extern rfc_CMD_PROP_TX_t RF_cmdPropTx;

// RF Core API Overrides
extern uint32_t pOverrides[];

#endif // _SMARTRF_SETTINGS_433_H_
