#ifndef LORA_CMWX1ZZABZ_h
#define LORA_CMWX1ZZABZ_h

#include "ArduinoWrapper.h"
#include <stdint.h>

#define LORA_NO_ERROR			    0
#define LORA_ERROR_BUSY			  1
#define LORA_ERROR_JOINED		  2

class LORA_CMWX1ZZABZ {
	public:
		LORA_CMWX1ZZABZ();
		void initAndJoin(); // OTAA: only once called if possible, generates DEV data that is stored in RAM, once joined stays joined in sleep (also if no gateway reachable), busy = 1, joined = 0 until connected (automatic retry after 2.5 minutes)
		bool isBusy();
		bool joined();
		uint8_t sendByte();

		const char *appEui = "70B3D57ED002EFFE"; 					// generated by TTN, identifies end application
		const char *appKey = "32165526D02D88F61A69549D5A5A8AE8"; 	// generated by TTN, only for OTAA
		char devEui[32]; 											// from my unique Murata device, here: 3834343075377f17
};

#endif
